version: '3.5'
services:
  db-mongo:
    image: mongo:4.4.0
    container_name: short-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: url-shortener
    volumes:
      - ./volumes/mongodb:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - short-url-net

  mongo-express:
    image: mongo-express:0.54.0
    container_name: short-mongo-express
    restart: always
    ports:
      - 8300:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    links:
      - db-mongo:mongo
    networks:
      - short-url-net

  redis:
    image: redis:6.0.6-alpine
    container_name: short-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis:/data
    networks:
      - short-url-net

networks:
  short-url-net:
    name: short-url-net
