version: '3'
services:
  db-mongo:
    image: mongo:4.4.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./volumes/mongodb:/data/db
    networks:
      - short-url-net

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8300:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    links:
      - db-mongo:mongo
    networks:
      - short-url-net

networks:
  short-url-net:
